### ISSUE TITLE
Unable to get the pretrained BERTNLU model.

### ISSUE THREAD

**Issue by sunnweiwei** [thu-coai/Convlab-2#238]
I am unable to download the pre-trained model when I execute the following code:
```
user_nlu = BERTNLU(mode='sys', config_file='multiwoz_sys_context.json', model_file='https://convlab.blob.core.windows.net/convlab-2/bert_multiwoz_sys_context.zip')
```
The program reports the following error:
```
intent num: 65
tag num: 319
Load from model_file param
Load from https://convlab.blob.core.windows.net/convlab-2/bert_multiwoz_sys_context.zip
Traceback (most recent call last):
  File "***", line 23, in <module>
    user_nlu = BERTNLU(mode='sys', config_file='multiwoz_sys_context.json', model_file='https://convlab.blob.core.windows.net/convlab-2/bert_multiwoz_sys_context.zip')
  File "***/ConvLab-2-master/convlab2/nlu/jointBERT/multiwoz/nlu.py", line 47, in __init__
    archive_file = cached_path(model_file)
  File "***/ConvLab-2-master/convlab2/util/file_util.py", line 13, in cached_path
    return allennlp_cached_path(file_path, cached_dir)
  File "***/ConvLab-2-master/convlab2/util/allennlp_file_utils.py", line 144, in cached_path
    return get_from_cache(url_or_filename, cache_dir)
  File "***/ConvLab-2-master/convlab2/util/allennlp_file_utils.py", line 271, in get_from_cache
    raise IOError("HEAD request failed for url {} with status code {}"
OSError: HEAD request failed for url https://convlab.blob.core.windows.net/convlab-2/bert_multiwoz_sys_context.zip with status code 404
```
Is there any solution please?  Thanks!

**Comment by bmanasi** [comment]
Facing the same issue for all the models in NLU module

**Comment by zqwerty** [comment]
It seems that the link is broken. Will try to check the cloud storage ASAP.

**Comment by zqwerty** [comment]
@sunnweiwei @bmanasi I've uploaded all ConvLab-2 models to [Hugging face](https://huggingface.co/ConvLab/ConvLab-2_models). You can change the URL to use the corresponding model.

**Comment by sunnweiwei** [comment]
Thanks, it works!

**Comment by bmanasi** [comment]
@sunnweiwei Could you help me out with where all to change the URL's? I changed it in the "ConvLab-2/blob/master/convlab2/nlu/jointBERT/multiwoz/nlu.py" at two places but its still throwing the same error.

**Comment by sunnweiwei** [comment]
I download the model files from the huggingface, and modify the code in line [53] in"convlab2/nlu/jointBERT/multiwoz/nlu.py".
Previous:
```
[52] model = JointBERT(config['model'], DEVICE, dataloader.tag_dim, dataloader.intent_dim)
[53] model.load_state_dict(torch.load(os.path.join(output_dir, 'pytorch_model.bin'), DEVICE))
[54] model.to(DEVICE)
[55] model.eval()
```
Now:
```
[52] model = JointBERT(config['model'], DEVICE, dataloader.tag_dim, dataloader.intent_dim)
[53] model.load_state_dict(torch.load('my_path/output/sys_context/pytorch_model.bin', map_location=lambda storage, loc: storage), strict=False)
[54] model.to(DEVICE)
[55] model.eval()
```

**Comment by bmanasi** [comment]
Actually I am working on colab and not locally. So i tried to do the following (mentioned in readme of convlab2 github) : 

![image](https://user-images.githubusercontent.com/40319992/199999940-43b812fe-3a88-49ec-a612-888192757f5d.png)

Here, in model_file, I pass the new hugging face url. But I get the error that the file is not a zipfile. Any idea how to resolve it?
